movie_sites:
  imdb:
    xpaths: 
      title: '//div[@class="title_wrapper"]/child::*/text()'
      duration: '//div[@class="title_wrapper"]//div[contains(@class, "subtext")]//time/text()'
      certificate: '//div[@class="title_wrapper"]//div[contains(@class, "subtext")]/text()'
      year_release: '//div[@class="title_wrapper"]//span[contains(@id, "titleYear")]/child::*/text()'
      release_date: '//div[@id="titleDetails"]//*[contains(text(), "Release Date")]/following-sibling::text()'
      keywords: '//div[child::*[contains(text(), "Plot Keywords")]]//span/text()'
      genres: '//div[@class="article" and @id="titleStoryLine"]//*[preceding-sibling::*[contains(text(), "Genres")]]/text()'
      country: '//div[@id="titleDetails"]//*[preceding-sibling::*[contains(text(), "Country")]]/text()'
      language: '//div[@id="titleDetails"]//*[preceding-sibling::*[contains(text(), "Language")]]/text()'
      aka: '//div[@id="titleDetails"]//*[contains(text(), "Also Known As")]/following-sibling::text()'
      color: '//div[@id="titleDetails"]//*[preceding-sibling::*[contains(text(), "Color")]]/text()'
      budget: '//div[@id="titleDetails"]//*[contains(text(), "Budget")]/following-sibling::text()'
      gross_usa: '//div[@id="titleDetails"]//*[contains(text(), "Gross USA")]/following-sibling::text()'
      sound_mix: '//div[@id="titleDetails"]//*[preceding-sibling::*[contains(text(), "Sound Mix")]]/text()'
      aspect_ratio: '//div[@id="titleDetails"]//*[contains(text(), "Aspect Ratio")]/following-sibling::text()'
      filming_locations: '//div[@id="titleDetails"]//*[preceding-sibling::*[contains(text(), "Filming Locations")]]/text()'
      cumulative_gross: '//div[@id="titleDetails"]//*[contains(text(), "Cumulative Worldwide Gross")]/following-sibling::text()'
      opening_weekend_usa: '//div[@id="titleDetails"]//*[contains(text(), "Opening Weekend USA")]/following-sibling::text()'
      link_to_reviews_page: '//div[@class="article" and @id="titleUserReviewsTeaser"]//*[preceding-sibling::*[contains(text(), "Review this title")]]/@href'
      rating: '//span[@itemprop="ratingValue"]/descendant::text()'
      rating_count: '//span[@itemprop="ratingCount"]/descendant::text()'
      director: '//div[contains(@class, "plot_summary")]//*[contains(text(), "Director")]/following::*/text()'
      writers: '//*[child::*[contains(text(), "Writers")]]/a/text()'
      stars: '//div[child::*[contains(text(), "Stars")]]/a[(following-sibling::span)]/text()'
      summary: '//div[@class="summary_text"]/text()'
      cast: '//table[@class="cast_list"]//a[contains(@href, "name")]/text()'
      storyline: //div[@id="titleStoryLine"]//p/span/text()
      poster: '//*[parent::div[@class="poster"]]/@href'
